voices = [('Alex', 'Alex - Male - English (United States)', ''),
('Karen', 'Karen - Female - English (Australia)', ''),
('Alice', 'Alice - Female - italiano (Italia)', ''),
('Alva', 'Alva - Female - svenska (Sverige)', ''),
('Amelie', 'Amelie - Female - français (Canada)', ''),
('Anna', 'Anna - Female - Deutsch (Deutschland)', ''),
('Carmit', 'Carmit - Female - עברית (ישראל)', ''),
('Damayanti', 'Damayanti - Female - Indonesia (Indonesia)', ''),
('Daniel', 'Daniel - Male - English (United Kingdom)', ''),
('Diego', 'Diego - Male - español (Argentina)', ''),
('Ellen', 'Ellen - Female - Nederlands (België)', ''),
('Fiona', 'Fiona - Female - en-scotland', ''),
('Fred', 'Fred - Male - English (United States)', ''),
('Ioana', 'Ioana - Female - română (România)', ''),
('Joana', 'Joana - Female - português (Portugal)', ''),
('Jorge', 'Jorge - Male - español (España)', ''),
('Juan', 'Juan - Male - español (México)', ''),
('Kanya', 'Kanya - Female - ไทย (ไทย)', ''),
('Kyoko', 'Kyoko - Female - 日本語 (日本)', ''),
('Laura', 'Laura - Female - slovenčina (Slovensko)', ''),
('Luca', 'Luca - Male - italiano (Italia)', ''),
('Luciana', 'Luciana - Female - português (Brasil)', ''),
('Maged', 'Maged - Male - العربية (المملكة العربية السعودية)', ''),
('Mariska', 'Mariska - Female - magyar (Magyarország)', ''),
('Mei-jia', 'Mei-jia - Female - zh_TW', ''),
('Melina', 'Melina - Female - Ελληνικά (Ελλάδα)', ''),
('Milena', 'Milena - Female - русский (Россия)', ''),
('Moira', 'Moira - Female - English (Ireland)', ''),
('Monica', 'Monica - Female - español (España)', ''),
('Nora', 'Nora - Female - norsk bokmål (Norge)', ''),
('Paulina', 'Paulina - Female - español (México)', ''),
('Rishi', 'Rishi - Male - English (India)', ''),
('Samantha', 'Samantha - Female - English (United States)', ''),
('Sara', 'Sara - Female - dansk (Danmark)', ''),
('Satu', 'Satu - Female - suomi (Suomi)', ''),
('Sin-ji', 'Sin-ji - Female - zh_HK', ''),
('Tessa', 'Tessa - Female - English (South Africa)', ''),
('Thomas', 'Thomas - Male - français (France)', ''),
('Ting-ting', 'Ting-ting - Female - zh_CN', ''),
('Veena', 'Veena - Female - English (India)', ''),
('Victoria', 'Victoria - Female - English (United States)', ''),
('Xander', 'Xander - Male - Nederlands (Nederland)', ''),
('Yelda', 'Yelda - Female - Türkçe (Türkiye)', ''),
('Yuna', 'Yuna - Female - 한국어 (대한민국)', ''),
('Yuri', 'Yuri - Male - русский (Россия)', ''),
('Zosia', 'Zosia - Female - polski (Polska)', ''),
('Zuzana', 'Zuzana - Female - čeština (Česko)', '')]