voices = [('17', 'Karen - Female - English (Australia)', ''),
('0', 'Alex - Male - English (United States)', ''),
('1', 'Alice - Female - italiano (Italia)', ''),
('2', 'Alva - Female - svenska (Sverige)', ''),
('3', 'Amelie - Female - français (Canada)', ''),
('4', 'Anna - Female - Deutsch (Deutschland)', ''),
('5', 'Carmit - Female - עברית (ישראל)', ''),
('6', 'Damayanti - Female - Indonesia (Indonesia)', ''),
('7', 'Daniel - Male - English (United Kingdom)', ''),
('8', 'Diego - Male - español (Argentina)', ''),
('9', 'Ellen - Female - Nederlands (België)', ''),
('10', 'Fiona - Female - en-scotland', ''),
('11', 'Fred - Male - English (United States)', ''),
('12', 'Ioana - Female - română (România)', ''),
('13', 'Joana - Female - português (Portugal)', ''),
('14', 'Jorge - Male - español (España)', ''),
('15', 'Juan - Male - español (México)', ''),
('16', 'Kanya - Female - ไทย (ไทย)', ''),
('18', 'Kyoko - Female - 日本語 (日本)', ''),
('19', 'Laura - Female - slovenčina (Slovensko)', ''),
('20', 'Lekha - Female - हिन्दी (भारत)', ''),
('21', 'Luca - Male - italiano (Italia)', ''),
('22', 'Luciana - Female - português (Brasil)', ''),
('23', 'Maged - Male - العربية (المملكة العربية السعودية)', ''),
('24', 'Mariska - Female - magyar (Magyarország)', ''),
('25', 'Mei-jia - Female - zh_TW', ''),
('26', 'Melina - Female - Ελληνικά (Ελλάδα)', ''),
('27', 'Milena - Female - русский (Россия)', ''),
('28', 'Moira - Female - English (Ireland)', ''),
('29', 'Monica - Female - español (España)', ''),
('30', 'Nora - Female - norsk bokmål (Norge)', ''),
('31', 'Paulina - Female - español (México)', ''),
('32', 'Rishi - Male - English (India)', ''),
('33', 'Samantha - Female - English (United States)', ''),
('34', 'Sara - Female - dansk (Danmark)', ''),
('35', 'Satu - Female - suomi (Suomi)', ''),
('36', 'Sin-ji - Female - zh_HK', ''),
('37', 'Tessa - Female - English (South Africa)', ''),
('38', 'Thomas - Male - français (France)', ''),
('39', 'Ting-ting - Female - zh_CN', ''),
('40', 'Veena - Female - English (India)', ''),
('41', 'Victoria - Female - English (United States)', ''),
('42', 'Xander - Male - Nederlands (Nederland)', ''),
('43', 'Yelda - Female - Türkçe (Türkiye)', ''),
('44', 'Yuna - Female - 한국어 (대한민국)', ''),
('45', 'Yuri - Male - русский (Россия)', ''),
('46', 'Zosia - Female - polski (Polska)', ''),
('47', 'Zuzana - Female - čeština (Česko)', '')]